### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ralfz123** [ralfz123/frontend-applications#1]
**Applicatie**:
- [x] Toekomstvisie--> Hoe zie je dit over 20 jaar? "_Jantje moet dan geen laadpaal halen want ze zijn dan al bij de voordeur geplaatst_." --> Waarom?
- [x] Toekomstvisie img's beeld van future
- [x] Naar David zijn feedback kijken TeamsDM
- [x] Dataviz interactief zoals bij FA --> input elements
- [x] Conclusies adhv dataviz
- [x]  Content van components dynamisch inladen in SPA
- [ ] {Bonus} Local storage (api data) bij refresh is hij zelfde (settings input filter)
- [x] Schrijven: Toekomstbeeld, intro, feit van de dag
- [ ] SVG: goede width geven (viewBox docs lezen)
- [ ] 1. j st checken
- [ ] Bijr beoord
- [ ] Deloy GH
- [ ] {Bonus} Dynamische feit selfmade dataset - > on refresh (random)

**Docs**:
- [x] Hooks
- [x] Classes
- [x] State (lifecycleMethods--> bulletten en klein vb erbij)
- [x] Props
- [x] create-react-app
- [x] JSX
- [x] https://github.com/ralfz123/frontend-applications/wiki/D3-Integratie-in-framework
- [ ] https://github.com/ralfz123/frontend-applications/wiki/Moeilijkheden
- [ ] https://github.com/ralfz123/frontend-applications/wiki/Wat-heb-ik-geleerd%3F
- [ ] https://github.com/ralfz123/frontend-applications/wiki/Proces --  welk pacakges kiezen, hoe gaan die mij helpen
- [x] https://github.com/ralfz123/frontend-applications/wiki/Eindproduct
- [ ] framework discussie eigen argumenten aanvullen
- [ ] README deploy uitschrijven EN

[Peer review](https://github.com/cmda-tt/course-20-21/blob/master/pages/frontend-applications/peerReview.md#review) even door spitten
